services:
  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - './backend/:/usr/app/'
      - '/usr/app/node_modules'
    ports:
      - '3001:3001'

  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - './frontend/:/usr/app/'
      - '/usr/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
